name: Update Niconico Fixtures

on:
  # Daily execution at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

  # Manual execution
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  update-fixtures:
    name: Update Niconico Fixtures
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-python-

      - name: Install Music Assistant server (editable)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          # Install Music Assistant from the main repository
          pip install -e git+https://github.com/music-assistant/server.git#egg=music_assistant

      - name: Update Niconico fixtures
        env:
          NICONICO_SESSION: ${{ secrets.NICONICO_SESSION }}
        run: |
          source .venv/bin/activate
          python scripts/main.py 2>&1 | tee fixture-update.log

      - name: Check for fixture changes
        id: check_changes
        run: |
          if [ ! -d "generated/fixtures" ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No generated fixtures directory found"
          elif git diff --quiet generated/fixtures/; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No fixture changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Fixture changes detected"
            git diff --name-only generated/fixtures/ > changed-files.txt
            echo "file_count=$(git diff --name-only generated/fixtures/ | wc -l)" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add generated/
          git commit -m "chore: Update Niconico fixtures [automated]"
          git push

      - name: Create issue for fixture updates
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            const fileCount = '${{ steps.check_changes.outputs.file_count }}';
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            const issueBody = `## Fixture Update Summary

            **Date:** ${date}
            **Changed Files:** ${fileCount}
            **Workflow Run:** [View Details](${runUrl})

            ### Next Steps

            The fixtures have been automatically updated and committed to this repository.

            To apply these changes to the Music Assistant server:

            1. Review the changes in the [latest commit](https://github.com/${context.repo.owner}/${context.repo.repo}/commits/main)
            2. Download the artifact from the [workflow run](${runUrl}) to see the full update log
            3. If the changes look correct, copy \`generated/fixtures/\` to \`music-assistant/server/tests/providers/nicovideo/fixtures/\`
            4. Create a PR in the server repository with the updated fixtures

            **Artifact:** The full update log is available as an artifact named \`fixture-update-log\` in the workflow run.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Automated] Fixture Update - ${date}`,
              body: issueBody,
              labels: ['automated', 'fixture-update']
            });

      - name: Upload fixture update log
        if: failure() || steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: fixture-update-log
          path: fixture-update.log
          retention-days: 30
